#!/bin/bash
# Test Ansible Deployment in Clean GCP Project
# Automated test script following CLEAN_PROJECT_TEST_GUIDE.md

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEST_INVENTORY="$SCRIPT_DIR/inventory/test.yml"
LOG_FILE="$SCRIPT_DIR/test-deployment-$(date +%Y%m%d-%H%M%S).log"

# Functions
log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1" | tee -a "$LOG_FILE"
}

log_error() {
    echo -e "${RED}[$(date +'%Y-%m-%d %H:%M:%S')] ERROR:${NC} $1" | tee -a "$LOG_FILE"
}

log_warning() {
    echo -e "${YELLOW}[$(date +'%Y-%m-%d %H:%M:%S')] WARNING:${NC} $1" | tee -a "$LOG_FILE"
}

log_info() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')] INFO:${NC} $1" | tee -a "$LOG_FILE"
}

check_command() {
    if ! command -v "$1" &> /dev/null; then
        log_error "$1 is not installed. Please install it first."
        exit 1
    fi
}

confirm() {
    read -p "$1 (yes/no): " response
    case "$response" in
        [yY][eE][sS]|[yY]) return 0 ;;
        *) return 1 ;;
    esac
}

# Phase 1: Pre-Flight Checks
phase1_preflight() {
    log "=== Phase 1: Pre-Flight Checks ==="

    # Check prerequisites
    log_info "Checking prerequisites..."
    check_command ansible
    check_command gcloud
    check_command docker
    check_command jq
    check_command curl

    # Version checks
    log_info "Ansible version: $(ansible --version | head -1)"
    log_info "gcloud version: $(gcloud version | grep 'Google Cloud SDK' | head -1)"
    log_info "Docker version: $(docker --version)"

    # Check Ansible collections
    log_info "Checking Ansible collections..."
    if ! ansible-galaxy collection list | grep -q "google.cloud"; then
        log_warning "google.cloud collection not found. Installing..."
        ansible-galaxy collection install google.cloud
    fi

    if ! ansible-galaxy collection list | grep -q "community.docker"; then
        log_warning "community.docker collection not found. Installing..."
        ansible-galaxy collection install community.docker
    fi

    log "✅ Pre-flight checks passed"
}

# Phase 2: Project Setup
phase2_project_setup() {
    log "=== Phase 2: Project Setup ==="

    # Get current project
    CURRENT_PROJECT=$(gcloud config get-value project 2>/dev/null || echo "")

    if [ -z "$CURRENT_PROJECT" ]; then
        log_error "No GCP project configured. Please run: gcloud config set project PROJECT_ID"
        exit 1
    fi

    log_info "Using GCP project: $CURRENT_PROJECT"
    log_info "Region: us-east1"

    # Check billing
    log_info "Checking billing status..."
    BILLING_ENABLED=$(gcloud billing projects describe "$CURRENT_PROJECT" \
        --format='value(billingEnabled)' 2>/dev/null || echo "false")

    if [ "$BILLING_ENABLED" != "True" ]; then
        log_error "Billing is not enabled for project: $CURRENT_PROJECT"
        log_info "Enable billing: https://console.cloud.google.com/billing"
        exit 1
    fi

    log "✅ Using project: $CURRENT_PROJECT"

    # Create/update test inventory
    log_info "Creating test inventory..."
    cat > "$TEST_INVENTORY" <<EOF
---
# Test Environment Inventory - Generated by test-clean-project.sh

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"

  vars:
    # Environment
    env_name: "test"

    # GCP Configuration
    gcp_project_id: "$CURRENT_PROJECT"
    gcp_region: "us-east1"

    # Cloud Run Configuration (minimal for testing)
    cloudrun_cpu: "1"
    cloudrun_memory: "1Gi"
    cloudrun_min_instances: 0
    cloudrun_max_instances: 3
    cloudrun_concurrency: 50

    # AlloyDB Configuration
    with_alloydb: false  # Start without AlloyDB

    # Test-specific settings
    allow_unauthenticated: true
    enable_auto_cleanup: false
    log_level: "DEBUG"

    # Build Configuration
    use_cloud_build: true
    build_machine_type: "E2_HIGHCPU_2"

    # Storage
    bucket_lifecycle_days: 1  # Aggressive cleanup
EOF

    log "✅ Project setup complete: $CURRENT_PROJECT"
}

# Phase 3: Dry-Run Test
phase3_dryrun() {
    log "=== Phase 3: Dry-Run Test ==="

    log_info "Running Ansible in check mode (no changes)..."

    if ansible-playbook "$SCRIPT_DIR/deploy.yml" \
        -i "$TEST_INVENTORY" \
        --check \
        -e "confirm_deployment=yes" \
        >> "$LOG_FILE" 2>&1; then
        log "✅ Dry-run test passed"
    else
        log_error "Dry-run test failed. Check $LOG_FILE for details."
        exit 1
    fi
}

# Phase 4: Deploy Base Infrastructure
phase4_deploy() {
    log "=== Phase 4: Deploy Base Infrastructure ==="

    log_warning "This will create GCP resources and incur costs (~$0.50-2.00 for test duration)"

    if ! confirm "Proceed with deployment?"; then
        log_info "Deployment cancelled by user"
        exit 0
    fi

    log_info "Starting deployment (this may take 12-18 minutes)..."
    log_info "Logs: $LOG_FILE"

    # Deploy with detailed logging
    if ansible-playbook "$SCRIPT_DIR/deploy.yml" \
        -i "$TEST_INVENTORY" \
        -e "confirm_deployment=yes" \
        -vv \
        | tee -a "$LOG_FILE"; then
        log "✅ Deployment completed successfully"
    else
        log_error "Deployment failed. Check $LOG_FILE for details."
        exit 1
    fi
}

# Phase 5: Verify Deployment
phase5_verify() {
    log "=== Phase 5: Verify Deployment ==="

    # Get service URL
    log_info "Getting Cloud Run service URL..."
    SERVICE_URL=$(gcloud run services describe code-index-mcp-test \
        --region=us-east1 \
        --format='value(status.url)' 2>/dev/null || echo "")

    if [ -z "$SERVICE_URL" ]; then
        log_error "Cloud Run service not found"
        exit 1
    fi

    log_info "Service URL: $SERVICE_URL"

    # Test health endpoint
    log_info "Testing health endpoint..."
    if curl -s -f "$SERVICE_URL/health" | jq . > /dev/null 2>&1; then
        log "✅ Health endpoint responding"
        curl -s "$SERVICE_URL/health" | jq . | tee -a "$LOG_FILE"
    else
        log_error "Health endpoint not responding"
        exit 1
    fi

    # Test SSE endpoint
    log_info "Testing SSE endpoint..."
    if timeout 5 curl -N -H "Accept: text/event-stream" "$SERVICE_URL/sse" 2>/dev/null | head -5 >> "$LOG_FILE"; then
        log "✅ SSE endpoint responding"
    else
        log_warning "SSE endpoint test inconclusive (this may be normal)"
    fi

    # Verify GCP resources
    log_info "Verifying GCP resources..."

    # Check service account
    if gcloud iam service-accounts describe \
        "code-index-cloudrun-test@$CURRENT_PROJECT.iam.gserviceaccount.com" \
        > /dev/null 2>&1; then
        log "✅ Service account created"
    else
        log_error "Service account not found"
    fi

    # Check buckets
    BUCKET_COUNT=$(gcloud storage buckets list | grep -c "code-index.*-test" || true)
    if [ "$BUCKET_COUNT" -eq 2 ]; then
        log "✅ GCS buckets created ($BUCKET_COUNT)"
    else
        log_warning "Expected 2 GCS buckets, found $BUCKET_COUNT"
    fi

    # Check secrets
    SECRET_COUNT=$(gcloud secrets list | grep -c "webhook-secret-test" || true)
    if [ "$SECRET_COUNT" -eq 3 ]; then
        log "✅ Webhook secrets created ($SECRET_COUNT)"
    else
        log_warning "Expected 3 webhook secrets, found $SECRET_COUNT"
    fi

    log "✅ Deployment verification passed"
}

# Phase 6: Test Utilities
phase6_utilities() {
    log "=== Phase 6: Test Utility Operations ==="

    # Generate API key
    log_info "Testing API key generation..."
    if ansible-playbook "$SCRIPT_DIR/utilities.yml" \
        -i "$TEST_INVENTORY" \
        -e "operation=generate_api_key" \
        -e "user_id=test-user" \
        >> "$LOG_FILE" 2>&1; then
        log "✅ API key generation successful"

        # Verify API key file exists
        if [ -f "$SCRIPT_DIR/api-key-test-user-test.txt" ]; then
            log_info "API key saved to: api-key-test-user-test.txt"
        fi
    else
        log_error "API key generation failed"
    fi
}

# Phase 7: Cleanup
phase7_cleanup() {
    log "=== Phase 7: Cleanup ==="

    log_warning "This will delete all test resources"

    if ! confirm "Proceed with cleanup?"; then
        log_info "Cleanup cancelled. Manual cleanup required."
        log_info "Run: ansible-playbook utilities.yml -i inventory/test.yml -e 'operation=teardown auto_approve=true delete_buckets=true'"
        return
    fi

    log_info "Running teardown..."
    if ansible-playbook "$SCRIPT_DIR/utilities.yml" \
        -i "$TEST_INVENTORY" \
        -e "operation=teardown" \
        -e "auto_approve=true" \
        -e "delete_buckets=true" \
        >> "$LOG_FILE" 2>&1; then
        log "✅ Cleanup completed"
    else
        log_error "Cleanup failed. Manual cleanup may be required."
    fi

    # Clean up local files
    log_info "Cleaning up local test files..."
    rm -f "$SCRIPT_DIR/api-key-test-user-test.txt"
    rm -f "$SCRIPT_DIR/deployment-summary-test-"*.md

    log "✅ Local cleanup completed"
}

# Phase 8: Summary
phase8_summary() {
    log "=== Phase 8: Test Summary ==="

    log_info "Test execution log: $LOG_FILE"

    # Count successes and failures
    SUCCESS_COUNT=$(grep -c "✅" "$LOG_FILE" || true)
    ERROR_COUNT=$(grep -c "ERROR" "$LOG_FILE" || true)

    log_info "Total checks passed: $SUCCESS_COUNT"
    if [ "$ERROR_COUNT" -gt 0 ]; then
        log_warning "Total errors encountered: $ERROR_COUNT"
        log_info "Review $LOG_FILE for details"
    else
        log "✅ All tests passed successfully!"
    fi

    # Final recommendations
    echo ""
    log "=== Next Steps ==="
    log_info "1. Review test results in: $LOG_FILE"
    log_info "2. If successful, consider production deployment:"
    log_info "   ansible-playbook deploy.yml -i inventory/prod.yml"
    log_info "3. For AlloyDB testing, provision with Terraform first:"
    log_info "   cd ../alloydb && terraform apply"
    log_info "4. Set up CI/CD integration (see CLEAN_PROJECT_TEST_GUIDE.md)"
}

# Main execution
main() {
    log "=========================================="
    log "Code Index MCP - Clean Project Test"
    log "=========================================="
    log "Start time: $(date)"
    log "Log file: $LOG_FILE"
    echo ""

    # Parse command line arguments
    SKIP_PREFLIGHT=false
    SKIP_DRYRUN=false
    SKIP_DEPLOY=false
    SKIP_UTILITIES=false
    SKIP_CLEANUP=false

    while [[ $# -gt 0 ]]; do
        case $1 in
            --skip-preflight)
                SKIP_PREFLIGHT=true
                shift
                ;;
            --skip-dryrun)
                SKIP_DRYRUN=true
                shift
                ;;
            --skip-deploy)
                SKIP_DEPLOY=true
                shift
                ;;
            --skip-utilities)
                SKIP_UTILITIES=true
                shift
                ;;
            --skip-cleanup)
                SKIP_CLEANUP=true
                shift
                ;;
            --help)
                echo "Usage: $0 [OPTIONS]"
                echo ""
                echo "Options:"
                echo "  --skip-preflight   Skip pre-flight checks"
                echo "  --skip-dryrun      Skip dry-run test"
                echo "  --skip-deploy      Skip deployment"
                echo "  --skip-utilities   Skip utility operations test"
                echo "  --skip-cleanup     Skip cleanup phase"
                echo "  --help             Show this help message"
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                echo "Use --help for usage information"
                exit 1
                ;;
        esac
    done

    # Execute phases
    [ "$SKIP_PREFLIGHT" = false ] && phase1_preflight
    [ "$SKIP_PREFLIGHT" = false ] && phase2_project_setup
    [ "$SKIP_DRYRUN" = false ] && phase3_dryrun
    [ "$SKIP_DEPLOY" = false ] && phase4_deploy
    [ "$SKIP_DEPLOY" = false ] && phase5_verify
    [ "$SKIP_UTILITIES" = false ] && phase6_utilities
    [ "$SKIP_CLEANUP" = false ] && phase7_cleanup
    phase8_summary

    log "=========================================="
    log "Test completed at: $(date)"
    log "=========================================="
}

# Run main function
main "$@"
