# Cloud Run Job configuration for automatic cleanup
# This job is triggered by Cloud Scheduler to clean up idle projects
#
# Deploy with:
#   gcloud run jobs replace cleanup-job.yaml --region=us-east1
#
# Manual execution:
#   gcloud run jobs execute code-index-cleanup-dev --region=us-east1
#
# ADR Reference: ADR 0002 - Automatic Resource Cleanup
#
# Note: This is a Cloud Run Job, not standard Kubernetes
# - Cloud Run doesn't use namespaces; isolation is at the project/region level
# - KSV110 warning about "default namespace" is not applicable to Cloud Run

apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: code-index-cleanup-dev
  # Cloud Run Jobs don't support namespaces - isolation is via GCP project/region
  labels:
    app: code-index-mcp
    component: cleanup
    environment: dev
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      taskCount: 1
      template:
        spec:
          # Maximum 10 minutes for cleanup
          timeoutSeconds: 600

          # Use same service account as main MCP server (default App Engine SA)
          serviceAccountName: tosinscloud@appspot.gserviceaccount.com

          maxRetries: 2

          # Pod-level security context
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000

          containers:
          - name: cleanup
            # Use the same image as the MCP server
            image: us-east1-docker.pkg.dev/tosinscloud/code-index-mcp/code-index-mcp-dev:latest

            # Run the cleanup script
            command:
            - python
            - -m
            - code_index_mcp.admin.run_cleanup

            # Cleanup configuration
            args:
            - --max-idle-days
            - "30"
            - --json  # Output in JSON format for logging

            # Environment variables
            env:
            - name: GCS_BUCKET_NAME
              value: code-index-projects-tosinscloud

            # Security context - run as non-root user
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: false  # Needed for temp files during cleanup

            # Resource limits
            resources:
              limits:
                cpu: "1"
                memory: 512Mi
