-- Local PostgreSQL Schema for Code Index MCP
-- Compatible with standard PostgreSQL + pgvector (no AlloyDB-specific features)

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- USERS TABLE
CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    api_key_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    storage_quota_gb INTEGER DEFAULT 50,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_api_key_hash ON users(api_key_hash);

-- PROJECTS TABLE
CREATE TABLE IF NOT EXISTS projects (
    project_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(user_id) ON DELETE CASCADE,
    project_name VARCHAR(255) NOT NULL,
    gcs_bucket VARCHAR(255),  -- Optional for local dev
    gcs_prefix VARCHAR(255),   -- Optional for local dev
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    last_indexed_at TIMESTAMPTZ,
    total_chunks INTEGER DEFAULT 0,
    total_files INTEGER DEFAULT 0,
    UNIQUE(user_id, project_name)
);

CREATE INDEX IF NOT EXISTS idx_projects_user_id ON projects(user_id);
CREATE INDEX IF NOT EXISTS idx_projects_last_indexed ON projects(last_indexed_at);

-- CODE_CHUNKS TABLE
CREATE TABLE IF NOT EXISTS code_chunks (
    chunk_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID REFERENCES projects(project_id) ON DELETE CASCADE,

    -- File information
    file_path TEXT NOT NULL,
    chunk_type VARCHAR(50) NOT NULL,
    chunk_name VARCHAR(255),
    line_start INTEGER,
    line_end INTEGER,
    language VARCHAR(50),

    -- Code content
    content TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,

    -- Vector embedding (768 dimensions for text-embedding-004)
    embedding vector(768),

    -- Metadata
    symbols JSONB,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(project_id, content_hash)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_code_chunks_project ON code_chunks(project_id);
CREATE INDEX IF NOT EXISTS idx_code_chunks_file_path ON code_chunks(file_path);
CREATE INDEX IF NOT EXISTS idx_code_chunks_language ON code_chunks(language);
CREATE INDEX IF NOT EXISTS idx_code_chunks_chunk_type ON code_chunks(chunk_type);
CREATE INDEX IF NOT EXISTS idx_code_chunks_content_hash ON code_chunks(content_hash);

-- HNSW vector index
CREATE INDEX IF NOT EXISTS code_chunks_embedding_idx ON code_chunks
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- ROW LEVEL SECURITY
ALTER TABLE code_chunks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS user_code_access ON code_chunks;
CREATE POLICY user_code_access ON code_chunks
FOR ALL
USING (
    project_id IN (
        SELECT project_id
        FROM projects
        WHERE user_id = current_setting('app.user_id', true)::UUID
    )
);

ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS user_project_access ON projects;
CREATE POLICY user_project_access ON projects
FOR ALL
USING (user_id = current_setting('app.user_id', true)::UUID);

-- HELPER FUNCTIONS

-- Set user context for RLS
CREATE OR REPLACE FUNCTION set_user_context(p_user_id UUID)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM set_config('app.user_id', p_user_id::TEXT, false);
END;
$$;

-- Semantic search (embeddings generated by Python MCP server, not database)
CREATE OR REPLACE FUNCTION semantic_search_code(
    p_user_id UUID,
    p_query_embedding vector(768),
    p_project_name TEXT DEFAULT NULL,
    p_language TEXT DEFAULT NULL,
    p_limit INTEGER DEFAULT 10
)
RETURNS TABLE (
    chunk_id UUID,
    project_name VARCHAR(255),
    file_path TEXT,
    chunk_name VARCHAR(255),
    chunk_type VARCHAR(50),
    line_range TEXT,
    language VARCHAR(50),
    content TEXT,
    symbols JSONB,
    similarity_score FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
    -- Set user context for RLS
    PERFORM set_user_context(p_user_id);

    -- Perform vector similarity search
    RETURN QUERY
    SELECT
        c.chunk_id,
        p.project_name,
        c.file_path,
        c.chunk_name,
        c.chunk_type,
        CONCAT(c.line_start::TEXT, '-', c.line_end::TEXT) AS line_range,
        c.language,
        c.content,
        c.symbols,
        (1 - (c.embedding <=> p_query_embedding)) AS similarity_score
    FROM code_chunks c
    JOIN projects p ON c.project_id = p.project_id
    WHERE
        p.user_id = p_user_id
        AND (p_project_name IS NULL OR p.project_name = p_project_name)
        AND (p_language IS NULL OR c.language = p_language)
        AND c.embedding IS NOT NULL
    ORDER BY c.embedding <=> p_query_embedding
    LIMIT p_limit;
END;
$$;

-- Project statistics
CREATE OR REPLACE FUNCTION get_project_stats(p_project_id UUID)
RETURNS TABLE (
    total_chunks BIGINT,
    total_files BIGINT,
    languages JSONB,
    chunk_types JSONB,
    avg_chunk_size FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        COUNT(*)::BIGINT AS total_chunks,
        COUNT(DISTINCT c.file_path)::BIGINT AS total_files,
        COALESCE(jsonb_object_agg(DISTINCT c.language, 1) FILTER (WHERE c.language IS NOT NULL), '{}'::jsonb) AS languages,
        COALESCE(jsonb_object_agg(DISTINCT c.chunk_type, 1), '{}'::jsonb) AS chunk_types,
        AVG(LENGTH(c.content))::FLOAT AS avg_chunk_size
    FROM code_chunks c
    WHERE c.project_id = p_project_id;
END;
$$;

-- Views
CREATE OR REPLACE VIEW project_overview AS
SELECT
    p.project_id,
    p.user_id,
    p.project_name,
    p.last_indexed_at,
    COUNT(c.chunk_id) AS total_chunks,
    COUNT(DISTINCT c.file_path) AS total_files,
    COUNT(DISTINCT c.language) AS language_count,
    MAX(c.updated_at) AS last_chunk_update
FROM projects p
LEFT JOIN code_chunks c ON p.project_id = c.project_id
GROUP BY p.project_id, p.user_id, p.project_name, p.last_indexed_at;

-- Schema version
CREATE TABLE IF NOT EXISTS schema_version (
    version INTEGER PRIMARY KEY,
    applied_at TIMESTAMPTZ DEFAULT NOW(),
    description TEXT
);

INSERT INTO schema_version (version, description)
VALUES (1, 'Local PostgreSQL schema: users, projects, code_chunks with vector embeddings')
ON CONFLICT (version) DO NOTHING;

-- Test user for local development
INSERT INTO users (email, api_key_hash, storage_quota_gb)
VALUES ('dev@localhost', 'local_dev_key', 100)
ON CONFLICT (email) DO NOTHING;

-- Completion
DO $$
BEGIN
    RAISE NOTICE '======================================';
    RAISE NOTICE 'Local PostgreSQL Schema Setup Complete!';
    RAISE NOTICE '======================================';
    RAISE NOTICE 'Tables: users, projects, code_chunks';
    RAISE NOTICE 'Extensions: vector, uuid-ossp';
    RAISE NOTICE 'Vector Index: HNSW (m=16, ef_construction=64)';
    RAISE NOTICE 'RLS: Enabled for multi-tenancy';
    RAISE NOTICE '======================================';
END $$;
